package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DanhMucBacSi generated by hbm2java
 */
public class DanhMucBacSi  implements java.io.Serializable {


     private int id;
     private KhoaPhong khoaPhong;
     private Serializable tenBacSi;
     private Set henKhamBenhs = new HashSet(0);

    public DanhMucBacSi() {
    }

	
    public DanhMucBacSi(int id) {
        this.id = id;
    }
    public DanhMucBacSi(int id, KhoaPhong khoaPhong, Serializable tenBacSi, Set henKhamBenhs) {
       this.id = id;
       this.khoaPhong = khoaPhong;
       this.tenBacSi = tenBacSi;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public KhoaPhong getKhoaPhong() {
        return this.khoaPhong;
    }
    
    public void setKhoaPhong(KhoaPhong khoaPhong) {
        this.khoaPhong = khoaPhong;
    }
    public Serializable getTenBacSi() {
        return this.tenBacSi;
    }
    
    public void setTenBacSi(Serializable tenBacSi) {
        this.tenBacSi = tenBacSi;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


