package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DichVu generated by hbm2java
 */
public class DichVu  implements java.io.Serializable {


     private int id;
     private Serializable moTa;
     private Set dichVuChiTiets = new HashSet(0);

    public DichVu() {
    }

	
    public DichVu(int id) {
        this.id = id;
    }
    public DichVu(int id, Serializable moTa, Set dichVuChiTiets) {
       this.id = id;
       this.moTa = moTa;
       this.dichVuChiTiets = dichVuChiTiets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(Serializable moTa) {
        this.moTa = moTa;
    }
    public Set getDichVuChiTiets() {
        return this.dichVuChiTiets;
    }
    
    public void setDichVuChiTiets(Set dichVuChiTiets) {
        this.dichVuChiTiets = dichVuChiTiets;
    }




}


