package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * DichVuChiTiet generated by hbm2java
 */
public class DichVuChiTiet  implements java.io.Serializable {


     private DichVuChiTietId id;
     private DichVu dichVu;
     private NgonNgu ngonNgu;
     private User user;
     private Serializable tenDichVu;
     private Serializable gioiThieu;
     private Serializable noiDung;
     private Serializable hinhAnh;
     private Date ngayTao;
     private Date ngayChinhSua;
     private int id_1;
     private Integer luotXem;

    public DichVuChiTiet() {
    }

	
    public DichVuChiTiet(DichVuChiTietId id, DichVu dichVu, NgonNgu ngonNgu, int id_1) {
        this.id = id;
        this.dichVu = dichVu;
        this.ngonNgu = ngonNgu;
        this.id_1 = id_1;
    }
    public DichVuChiTiet(DichVuChiTietId id, DichVu dichVu, NgonNgu ngonNgu, User user, Serializable tenDichVu, Serializable gioiThieu, Serializable noiDung, Serializable hinhAnh, Date ngayTao, Date ngayChinhSua, int id_1, Integer luotXem) {
       this.id = id;
       this.dichVu = dichVu;
       this.ngonNgu = ngonNgu;
       this.user = user;
       this.tenDichVu = tenDichVu;
       this.gioiThieu = gioiThieu;
       this.noiDung = noiDung;
       this.hinhAnh = hinhAnh;
       this.ngayTao = ngayTao;
       this.ngayChinhSua = ngayChinhSua;
       this.id_1 = id_1;
       this.luotXem = luotXem;
    }
   
    public DichVuChiTietId getId() {
        return this.id;
    }
    
    public void setId(DichVuChiTietId id) {
        this.id = id;
    }
    public DichVu getDichVu() {
        return this.dichVu;
    }
    
    public void setDichVu(DichVu dichVu) {
        this.dichVu = dichVu;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTenDichVu() {
        return this.tenDichVu;
    }
    
    public void setTenDichVu(Serializable tenDichVu) {
        this.tenDichVu = tenDichVu;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Date getNgayChinhSua() {
        return this.ngayChinhSua;
    }
    
    public void setNgayChinhSua(Date ngayChinhSua) {
        this.ngayChinhSua = ngayChinhSua;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }




}


