package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1



/**
 * DichVuChiTietId generated by hbm2java
 */
public class DichVuChiTietId  implements java.io.Serializable {


     private int fkNgonNgu;
     private int fkDichVu;

    public DichVuChiTietId() {
    }

    public DichVuChiTietId(int fkNgonNgu, int fkDichVu) {
       this.fkNgonNgu = fkNgonNgu;
       this.fkDichVu = fkDichVu;
    }
   
    public int getFkNgonNgu() {
        return this.fkNgonNgu;
    }
    
    public void setFkNgonNgu(int fkNgonNgu) {
        this.fkNgonNgu = fkNgonNgu;
    }
    public int getFkDichVu() {
        return this.fkDichVu;
    }
    
    public void setFkDichVu(int fkDichVu) {
        this.fkDichVu = fkDichVu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DichVuChiTietId) ) return false;
		 DichVuChiTietId castOther = ( DichVuChiTietId ) other; 
         
		 return (this.getFkNgonNgu()==castOther.getFkNgonNgu())
 && (this.getFkDichVu()==castOther.getFkDichVu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkNgonNgu();
         result = 37 * result + this.getFkDichVu();
         return result;
   }   


}


