package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private User user;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable hinhAnh;
     private Serializable link;
     private Date ngayTao;
     private Integer stt;
     private Boolean newTab;

    public Event() {
    }

	
    public Event(int id) {
        this.id = id;
    }
    public Event(int id, NgonNgu ngonNgu, User user, Serializable tieuDe, Serializable gioiThieu, Serializable hinhAnh, Serializable link, Date ngayTao, Integer stt, Boolean newTab) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.user = user;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.hinhAnh = hinhAnh;
       this.link = link;
       this.ngayTao = ngayTao;
       this.stt = stt;
       this.newTab = newTab;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Boolean getNewTab() {
        return this.newTab;
    }
    
    public void setNewTab(Boolean newTab) {
        this.newTab = newTab;
    }




}


