package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * GioiThieuChiTiet generated by hbm2java
 */
public class GioiThieuChiTiet  implements java.io.Serializable {


     private GioiThieuChiTietId id;
     private GioiThieu gioiThieu;
     private NgonNgu ngonNgu;
     private User user;
     private Serializable ten;
     private Serializable gioiThieu_1;
     private Serializable noiDung;
     private Serializable hinhAnh;
     private Date ngayTao;
     private Date ngayChinhSua;
     private int id_1;
     private Integer luotXem;

    public GioiThieuChiTiet() {
    }

	
    public GioiThieuChiTiet(GioiThieuChiTietId id, GioiThieu gioiThieu, NgonNgu ngonNgu, int id_1) {
        this.id = id;
        this.gioiThieu = gioiThieu;
        this.ngonNgu = ngonNgu;
        this.id_1 = id_1;
    }
    public GioiThieuChiTiet(GioiThieuChiTietId id, GioiThieu gioiThieu, NgonNgu ngonNgu, User user, Serializable ten, Serializable gioiThieu_1, Serializable noiDung, Serializable hinhAnh, Date ngayTao, Date ngayChinhSua, int id_1, Integer luotXem) {
       this.id = id;
       this.gioiThieu = gioiThieu;
       this.ngonNgu = ngonNgu;
       this.user = user;
       this.ten = ten;
       this.gioiThieu_1 = gioiThieu_1;
       this.noiDung = noiDung;
       this.hinhAnh = hinhAnh;
       this.ngayTao = ngayTao;
       this.ngayChinhSua = ngayChinhSua;
       this.id_1 = id_1;
       this.luotXem = luotXem;
    }
   
    public GioiThieuChiTietId getId() {
        return this.id;
    }
    
    public void setId(GioiThieuChiTietId id) {
        this.id = id;
    }
    public GioiThieu getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(GioiThieu gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTen() {
        return this.ten;
    }
    
    public void setTen(Serializable ten) {
        this.ten = ten;
    }
    public Serializable getGioiThieu_1() {
        return this.gioiThieu_1;
    }
    
    public void setGioiThieu_1(Serializable gioiThieu_1) {
        this.gioiThieu_1 = gioiThieu_1;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Date getNgayChinhSua() {
        return this.ngayChinhSua;
    }
    
    public void setNgayChinhSua(Date ngayChinhSua) {
        this.ngayChinhSua = ngayChinhSua;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }




}


