package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * GioiThieu generated by hbm2java
 */
public class GioiThieu  implements java.io.Serializable {


     private int id;
     private Serializable tenGioiThieu;
     private Set gioiThieuChiTiets = new HashSet(0);

    public GioiThieu() {
    }

	
    public GioiThieu(int id) {
        this.id = id;
    }
    public GioiThieu(int id, Serializable tenGioiThieu, Set gioiThieuChiTiets) {
       this.id = id;
       this.tenGioiThieu = tenGioiThieu;
       this.gioiThieuChiTiets = gioiThieuChiTiets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenGioiThieu() {
        return this.tenGioiThieu;
    }
    
    public void setTenGioiThieu(Serializable tenGioiThieu) {
        this.tenGioiThieu = tenGioiThieu;
    }
    public Set getGioiThieuChiTiets() {
        return this.gioiThieuChiTiets;
    }
    
    public void setGioiThieuChiTiets(Set gioiThieuChiTiets) {
        this.gioiThieuChiTiets = gioiThieuChiTiets;
    }




}


