package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GioKham generated by hbm2java
 */
public class GioKham  implements java.io.Serializable {


     private int id;
     private String gio;
     private Set henKhamBenhs = new HashSet(0);

    public GioKham() {
    }

	
    public GioKham(int id) {
        this.id = id;
    }
    public GioKham(int id, String gio, Set henKhamBenhs) {
       this.id = id;
       this.gio = gio;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGio() {
        return this.gio;
    }
    
    public void setGio(String gio) {
        this.gio = gio;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


