package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1



/**
 * GroupPermissionId generated by hbm2java
 */
public class GroupPermissionId  implements java.io.Serializable {


     private int fkGroup;
     private int fkPermission;

    public GroupPermissionId() {
    }

    public GroupPermissionId(int fkGroup, int fkPermission) {
       this.fkGroup = fkGroup;
       this.fkPermission = fkPermission;
    }
   
    public int getFkGroup() {
        return this.fkGroup;
    }
    
    public void setFkGroup(int fkGroup) {
        this.fkGroup = fkGroup;
    }
    public int getFkPermission() {
        return this.fkPermission;
    }
    
    public void setFkPermission(int fkPermission) {
        this.fkPermission = fkPermission;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupPermissionId) ) return false;
		 GroupPermissionId castOther = ( GroupPermissionId ) other; 
         
		 return (this.getFkGroup()==castOther.getFkGroup())
 && (this.getFkPermission()==castOther.getFkPermission());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkGroup();
         result = 37 * result + this.getFkPermission();
         return result;
   }   


}


