package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1



/**
 * GroupPermission generated by hbm2java
 */
public class GroupPermission  implements java.io.Serializable {


     private GroupPermissionId id;
     private Group group;
     private Permission permission;
     private Boolean allow;

    public GroupPermission() {
    }

	
    public GroupPermission(GroupPermissionId id, Group group, Permission permission) {
        this.id = id;
        this.group = group;
        this.permission = permission;
    }
    public GroupPermission(GroupPermissionId id, Group group, Permission permission, Boolean allow) {
       this.id = id;
       this.group = group;
       this.permission = permission;
       this.allow = allow;
    }
   
    public GroupPermissionId getId() {
        return this.id;
    }
    
    public void setId(GroupPermissionId id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public Boolean getAllow() {
        return this.allow;
    }
    
    public void setAllow(Boolean allow) {
        this.allow = allow;
    }




}


