package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * HoatDong generated by hbm2java
 */
public class HoatDong  implements java.io.Serializable {


     private int id;
     private LoaiHoatDong loaiHoatDong;
     private NgonNgu ngonNgu;
     private User userByFkNguoiSua;
     private User userByFkNguoiTao;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable hinhAnhMinhHoa;
     private Serializable noiDung;
     private Integer stt;
     private Integer luotXem;
     private Date ngayTao;
     private Serializable author;
     private Date ngaySua;

    public HoatDong() {
    }

	
    public HoatDong(int id) {
        this.id = id;
    }
    public HoatDong(int id, LoaiHoatDong loaiHoatDong, NgonNgu ngonNgu, User userByFkNguoiSua, User userByFkNguoiTao, Serializable tieuDe, Serializable gioiThieu, Serializable hinhAnhMinhHoa, Serializable noiDung, Integer stt, Integer luotXem, Date ngayTao, Serializable author, Date ngaySua) {
       this.id = id;
       this.loaiHoatDong = loaiHoatDong;
       this.ngonNgu = ngonNgu;
       this.userByFkNguoiSua = userByFkNguoiSua;
       this.userByFkNguoiTao = userByFkNguoiTao;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.hinhAnhMinhHoa = hinhAnhMinhHoa;
       this.noiDung = noiDung;
       this.stt = stt;
       this.luotXem = luotXem;
       this.ngayTao = ngayTao;
       this.author = author;
       this.ngaySua = ngaySua;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public LoaiHoatDong getLoaiHoatDong() {
        return this.loaiHoatDong;
    }
    
    public void setLoaiHoatDong(LoaiHoatDong loaiHoatDong) {
        this.loaiHoatDong = loaiHoatDong;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUserByFkNguoiSua() {
        return this.userByFkNguoiSua;
    }
    
    public void setUserByFkNguoiSua(User userByFkNguoiSua) {
        this.userByFkNguoiSua = userByFkNguoiSua;
    }
    public User getUserByFkNguoiTao() {
        return this.userByFkNguoiTao;
    }
    
    public void setUserByFkNguoiTao(User userByFkNguoiTao) {
        this.userByFkNguoiTao = userByFkNguoiTao;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getHinhAnhMinhHoa() {
        return this.hinhAnhMinhHoa;
    }
    
    public void setHinhAnhMinhHoa(Serializable hinhAnhMinhHoa) {
        this.hinhAnhMinhHoa = hinhAnhMinhHoa;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Serializable getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Serializable author) {
        this.author = author;
    }
    public Date getNgaySua() {
        return this.ngaySua;
    }
    
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }




}


