package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * HoiDapYkhoa generated by hbm2java
 */
public class HoiDapYkhoa  implements java.io.Serializable {


     private int id;
     private LoaiCauHoi loaiCauHoi;
     private NamSinh namSinh;
     private User user;
     private Serializable tieuDe;
     private Serializable noiDungCauHoi;
     private Serializable hoTenNguoiHoi;
     private Boolean gioiTinh;
     private Serializable noiDungTraLoi;
     private Date ngayGuiCauHoi;
     private Date ngayTraLoi;
     private Serializable nguoiTraLoi;
     private Boolean isShow;
     private Boolean daTraLoi;
     private Serializable email;
     private Serializable diaChi;
     private Serializable soDienThoai;

    public HoiDapYkhoa() {
    }

	
    public HoiDapYkhoa(int id) {
        this.id = id;
    }
    public HoiDapYkhoa(int id, LoaiCauHoi loaiCauHoi, NamSinh namSinh, User user, Serializable tieuDe, Serializable noiDungCauHoi, Serializable hoTenNguoiHoi, Boolean gioiTinh, Serializable noiDungTraLoi, Date ngayGuiCauHoi, Date ngayTraLoi, Serializable nguoiTraLoi, Boolean isShow, Boolean daTraLoi, Serializable email, Serializable diaChi, Serializable soDienThoai) {
       this.id = id;
       this.loaiCauHoi = loaiCauHoi;
       this.namSinh = namSinh;
       this.user = user;
       this.tieuDe = tieuDe;
       this.noiDungCauHoi = noiDungCauHoi;
       this.hoTenNguoiHoi = hoTenNguoiHoi;
       this.gioiTinh = gioiTinh;
       this.noiDungTraLoi = noiDungTraLoi;
       this.ngayGuiCauHoi = ngayGuiCauHoi;
       this.ngayTraLoi = ngayTraLoi;
       this.nguoiTraLoi = nguoiTraLoi;
       this.isShow = isShow;
       this.daTraLoi = daTraLoi;
       this.email = email;
       this.diaChi = diaChi;
       this.soDienThoai = soDienThoai;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public LoaiCauHoi getLoaiCauHoi() {
        return this.loaiCauHoi;
    }
    
    public void setLoaiCauHoi(LoaiCauHoi loaiCauHoi) {
        this.loaiCauHoi = loaiCauHoi;
    }
    public NamSinh getNamSinh() {
        return this.namSinh;
    }
    
    public void setNamSinh(NamSinh namSinh) {
        this.namSinh = namSinh;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getNoiDungCauHoi() {
        return this.noiDungCauHoi;
    }
    
    public void setNoiDungCauHoi(Serializable noiDungCauHoi) {
        this.noiDungCauHoi = noiDungCauHoi;
    }
    public Serializable getHoTenNguoiHoi() {
        return this.hoTenNguoiHoi;
    }
    
    public void setHoTenNguoiHoi(Serializable hoTenNguoiHoi) {
        this.hoTenNguoiHoi = hoTenNguoiHoi;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Serializable getNoiDungTraLoi() {
        return this.noiDungTraLoi;
    }
    
    public void setNoiDungTraLoi(Serializable noiDungTraLoi) {
        this.noiDungTraLoi = noiDungTraLoi;
    }
    public Date getNgayGuiCauHoi() {
        return this.ngayGuiCauHoi;
    }
    
    public void setNgayGuiCauHoi(Date ngayGuiCauHoi) {
        this.ngayGuiCauHoi = ngayGuiCauHoi;
    }
    public Date getNgayTraLoi() {
        return this.ngayTraLoi;
    }
    
    public void setNgayTraLoi(Date ngayTraLoi) {
        this.ngayTraLoi = ngayTraLoi;
    }
    public Serializable getNguoiTraLoi() {
        return this.nguoiTraLoi;
    }
    
    public void setNguoiTraLoi(Serializable nguoiTraLoi) {
        this.nguoiTraLoi = nguoiTraLoi;
    }
    public Boolean getIsShow() {
        return this.isShow;
    }
    
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }
    public Boolean getDaTraLoi() {
        return this.daTraLoi;
    }
    
    public void setDaTraLoi(Boolean daTraLoi) {
        this.daTraLoi = daTraLoi;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }
    public Serializable getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(Serializable soDienThoai) {
        this.soDienThoai = soDienThoai;
    }




}


