package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ImagePage generated by hbm2java
 */
public class ImagePage  implements java.io.Serializable {


     private ImagePageId id;
     private NgonNgu ngonNgu;
     private Serializable imagePath;
     private Serializable tieuDe;
     private int id_1;

    public ImagePage() {
    }

	
    public ImagePage(ImagePageId id, NgonNgu ngonNgu, int id_1) {
        this.id = id;
        this.ngonNgu = ngonNgu;
        this.id_1 = id_1;
    }
    public ImagePage(ImagePageId id, NgonNgu ngonNgu, Serializable imagePath, Serializable tieuDe, int id_1) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.imagePath = imagePath;
       this.tieuDe = tieuDe;
       this.id_1 = id_1;
    }
   
    public ImagePageId getId() {
        return this.id;
    }
    
    public void setId(ImagePageId id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(Serializable imagePath) {
        this.imagePath = imagePath;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }




}


