package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ImagePageId generated by hbm2java
 */
public class ImagePageId  implements java.io.Serializable {


     private int fkNgonNgu;
     private Serializable pageName;

    public ImagePageId() {
    }

    public ImagePageId(int fkNgonNgu, Serializable pageName) {
       this.fkNgonNgu = fkNgonNgu;
       this.pageName = pageName;
    }
   
    public int getFkNgonNgu() {
        return this.fkNgonNgu;
    }
    
    public void setFkNgonNgu(int fkNgonNgu) {
        this.fkNgonNgu = fkNgonNgu;
    }
    public Serializable getPageName() {
        return this.pageName;
    }
    
    public void setPageName(Serializable pageName) {
        this.pageName = pageName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImagePageId) ) return false;
		 ImagePageId castOther = ( ImagePageId ) other; 
         
		 return (this.getFkNgonNgu()==castOther.getFkNgonNgu())
 && ( (this.getPageName()==castOther.getPageName()) || ( this.getPageName()!=null && castOther.getPageName()!=null && this.getPageName().equals(castOther.getPageName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkNgonNgu();
         result = 37 * result + ( getPageName() == null ? 0 : this.getPageName().hashCode() );
         return result;
   }   


}


