package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KhoaPhong generated by hbm2java
 */
public class KhoaPhong  implements java.io.Serializable {


     private int id;
     private LoaiKhoaPhong loaiKhoaPhong;
     private NgonNgu ngonNgu;
     private Serializable tieuDeKhoa;
     private Serializable tenKhoaPhong;
     private Serializable gioiThieu;
     private Serializable noiDung;
     private Date ngayCapNhat;
     private String userModify;
     private Serializable hinhAnhDaiDien;
     private Boolean henKhamBenh;
     private Integer stt;
     private Integer luotXem;
     private Set danhMucBacSis = new HashSet(0);
     private Set users = new HashSet(0);

    public KhoaPhong() {
    }

	
    public KhoaPhong(int id) {
        this.id = id;
    }
    public KhoaPhong(int id, LoaiKhoaPhong loaiKhoaPhong, NgonNgu ngonNgu, Serializable tieuDeKhoa, Serializable tenKhoaPhong, Serializable gioiThieu, Serializable noiDung, Date ngayCapNhat, String userModify, Serializable hinhAnhDaiDien, Boolean henKhamBenh, Integer stt, Integer luotXem, Set danhMucBacSis, Set users) {
       this.id = id;
       this.loaiKhoaPhong = loaiKhoaPhong;
       this.ngonNgu = ngonNgu;
       this.tieuDeKhoa = tieuDeKhoa;
       this.tenKhoaPhong = tenKhoaPhong;
       this.gioiThieu = gioiThieu;
       this.noiDung = noiDung;
       this.ngayCapNhat = ngayCapNhat;
       this.userModify = userModify;
       this.hinhAnhDaiDien = hinhAnhDaiDien;
       this.henKhamBenh = henKhamBenh;
       this.stt = stt;
       this.luotXem = luotXem;
       this.danhMucBacSis = danhMucBacSis;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public LoaiKhoaPhong getLoaiKhoaPhong() {
        return this.loaiKhoaPhong;
    }
    
    public void setLoaiKhoaPhong(LoaiKhoaPhong loaiKhoaPhong) {
        this.loaiKhoaPhong = loaiKhoaPhong;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTieuDeKhoa() {
        return this.tieuDeKhoa;
    }
    
    public void setTieuDeKhoa(Serializable tieuDeKhoa) {
        this.tieuDeKhoa = tieuDeKhoa;
    }
    public Serializable getTenKhoaPhong() {
        return this.tenKhoaPhong;
    }
    
    public void setTenKhoaPhong(Serializable tenKhoaPhong) {
        this.tenKhoaPhong = tenKhoaPhong;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public String getUserModify() {
        return this.userModify;
    }
    
    public void setUserModify(String userModify) {
        this.userModify = userModify;
    }
    public Serializable getHinhAnhDaiDien() {
        return this.hinhAnhDaiDien;
    }
    
    public void setHinhAnhDaiDien(Serializable hinhAnhDaiDien) {
        this.hinhAnhDaiDien = hinhAnhDaiDien;
    }
    public Boolean getHenKhamBenh() {
        return this.henKhamBenh;
    }
    
    public void setHenKhamBenh(Boolean henKhamBenh) {
        this.henKhamBenh = henKhamBenh;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }
    public Set getDanhMucBacSis() {
        return this.danhMucBacSis;
    }
    
    public void setDanhMucBacSis(Set danhMucBacSis) {
        this.danhMucBacSis = danhMucBacSis;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


