package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LichNgay generated by hbm2java
 */
public class LichNgay  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tenThu;
     private Set lichKhams = new HashSet(0);

    public LichNgay() {
    }

	
    public LichNgay(int id) {
        this.id = id;
    }
    public LichNgay(int id, NgonNgu ngonNgu, Serializable tenThu, Set lichKhams) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tenThu = tenThu;
       this.lichKhams = lichKhams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTenThu() {
        return this.tenThu;
    }
    
    public void setTenThu(Serializable tenThu) {
        this.tenThu = tenThu;
    }
    public Set getLichKhams() {
        return this.lichKhams;
    }
    
    public void setLichKhams(Set lichKhams) {
        this.lichKhams = lichKhams;
    }




}


