package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1



/**
 * LichKhamId generated by hbm2java
 */
public class LichKhamId  implements java.io.Serializable {


     private int fkLichNgay;
     private int fkPhongKham;

    public LichKhamId() {
    }

    public LichKhamId(int fkLichNgay, int fkPhongKham) {
       this.fkLichNgay = fkLichNgay;
       this.fkPhongKham = fkPhongKham;
    }
   
    public int getFkLichNgay() {
        return this.fkLichNgay;
    }
    
    public void setFkLichNgay(int fkLichNgay) {
        this.fkLichNgay = fkLichNgay;
    }
    public int getFkPhongKham() {
        return this.fkPhongKham;
    }
    
    public void setFkPhongKham(int fkPhongKham) {
        this.fkPhongKham = fkPhongKham;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LichKhamId) ) return false;
		 LichKhamId castOther = ( LichKhamId ) other; 
         
		 return (this.getFkLichNgay()==castOther.getFkLichNgay())
 && (this.getFkPhongKham()==castOther.getFkPhongKham());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkLichNgay();
         result = 37 * result + this.getFkPhongKham();
         return result;
   }   


}


