package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * LichKham generated by hbm2java
 */
public class LichKham  implements java.io.Serializable {


     private LichKhamId id;
     private LichNgay lichNgay;
     private PhongKham phongKham;
     private Serializable sang;
     private Serializable chieu;

    public LichKham() {
    }

	
    public LichKham(LichKhamId id, LichNgay lichNgay, PhongKham phongKham) {
        this.id = id;
        this.lichNgay = lichNgay;
        this.phongKham = phongKham;
    }
    public LichKham(LichKhamId id, LichNgay lichNgay, PhongKham phongKham, Serializable sang, Serializable chieu) {
       this.id = id;
       this.lichNgay = lichNgay;
       this.phongKham = phongKham;
       this.sang = sang;
       this.chieu = chieu;
    }
   
    public LichKhamId getId() {
        return this.id;
    }
    
    public void setId(LichKhamId id) {
        this.id = id;
    }
    public LichNgay getLichNgay() {
        return this.lichNgay;
    }
    
    public void setLichNgay(LichNgay lichNgay) {
        this.lichNgay = lichNgay;
    }
    public PhongKham getPhongKham() {
        return this.phongKham;
    }
    
    public void setPhongKham(PhongKham phongKham) {
        this.phongKham = phongKham;
    }
    public Serializable getSang() {
        return this.sang;
    }
    
    public void setSang(Serializable sang) {
        this.sang = sang;
    }
    public Serializable getChieu() {
        return this.chieu;
    }
    
    public void setChieu(Serializable chieu) {
        this.chieu = chieu;
    }




}


