package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * LienHeKhachHang generated by hbm2java
 */
public class LienHeKhachHang  implements java.io.Serializable {


     private int id;
     private User user;
     private Serializable hoVaTen;
     private String dienThoaiNha;
     private String dienThoaiDiDong;
     private String email;
     private Serializable noiDung;
     private Date ngayGui;
     private Boolean daXem;
     private Date ngayXem;
     private Serializable tieuDe;

    public LienHeKhachHang() {
    }

	
    public LienHeKhachHang(int id) {
        this.id = id;
    }
    public LienHeKhachHang(int id, User user, Serializable hoVaTen, String dienThoaiNha, String dienThoaiDiDong, String email, Serializable noiDung, Date ngayGui, Boolean daXem, Date ngayXem, Serializable tieuDe) {
       this.id = id;
       this.user = user;
       this.hoVaTen = hoVaTen;
       this.dienThoaiNha = dienThoaiNha;
       this.dienThoaiDiDong = dienThoaiDiDong;
       this.email = email;
       this.noiDung = noiDung;
       this.ngayGui = ngayGui;
       this.daXem = daXem;
       this.ngayXem = ngayXem;
       this.tieuDe = tieuDe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getHoVaTen() {
        return this.hoVaTen;
    }
    
    public void setHoVaTen(Serializable hoVaTen) {
        this.hoVaTen = hoVaTen;
    }
    public String getDienThoaiNha() {
        return this.dienThoaiNha;
    }
    
    public void setDienThoaiNha(String dienThoaiNha) {
        this.dienThoaiNha = dienThoaiNha;
    }
    public String getDienThoaiDiDong() {
        return this.dienThoaiDiDong;
    }
    
    public void setDienThoaiDiDong(String dienThoaiDiDong) {
        this.dienThoaiDiDong = dienThoaiDiDong;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayGui() {
        return this.ngayGui;
    }
    
    public void setNgayGui(Date ngayGui) {
        this.ngayGui = ngayGui;
    }
    public Boolean getDaXem() {
        return this.daXem;
    }
    
    public void setDaXem(Boolean daXem) {
        this.daXem = daXem;
    }
    public Date getNgayXem() {
        return this.ngayXem;
    }
    
    public void setNgayXem(Date ngayXem) {
        this.ngayXem = ngayXem;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }




}


