package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * LienKetWebSite generated by hbm2java
 */
public class LienKetWebSite  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tieuDe;
     private Serializable link;
     private Integer stt;

    public LienKetWebSite() {
    }

	
    public LienKetWebSite(int id) {
        this.id = id;
    }
    public LienKetWebSite(int id, NgonNgu ngonNgu, Serializable tieuDe, Serializable link, Integer stt) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tieuDe = tieuDe;
       this.link = link;
       this.stt = stt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }




}


