package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiCauHoi generated by hbm2java
 */
public class LoaiCauHoi  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tenLoai;
     private Set hoiDapYkhoas = new HashSet(0);

    public LoaiCauHoi() {
    }

	
    public LoaiCauHoi(int id) {
        this.id = id;
    }
    public LoaiCauHoi(int id, NgonNgu ngonNgu, Serializable tenLoai, Set hoiDapYkhoas) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tenLoai = tenLoai;
       this.hoiDapYkhoas = hoiDapYkhoas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(Serializable tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getHoiDapYkhoas() {
        return this.hoiDapYkhoas;
    }
    
    public void setHoiDapYkhoas(Set hoiDapYkhoas) {
        this.hoiDapYkhoas = hoiDapYkhoas;
    }




}


