package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiTin generated by hbm2java
 */
public class LoaiTin  implements java.io.Serializable {


     private int id;
     private Serializable tenLoai;
     private Set tinTucs = new HashSet(0);

    public LoaiTin() {
    }

	
    public LoaiTin(int id) {
        this.id = id;
    }
    public LoaiTin(int id, Serializable tenLoai, Set tinTucs) {
       this.id = id;
       this.tenLoai = tenLoai;
       this.tinTucs = tinTucs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(Serializable tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getTinTucs() {
        return this.tinTucs;
    }
    
    public void setTinTucs(Set tinTucs) {
        this.tinTucs = tinTucs;
    }




}


