package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiKhoaPhong generated by hbm2java
 */
public class LoaiKhoaPhong  implements java.io.Serializable {


     private int id;
     private Serializable tenLoai;
     private Set khoaPhongs = new HashSet(0);

    public LoaiKhoaPhong() {
    }

	
    public LoaiKhoaPhong(int id) {
        this.id = id;
    }
    public LoaiKhoaPhong(int id, Serializable tenLoai, Set khoaPhongs) {
       this.id = id;
       this.tenLoai = tenLoai;
       this.khoaPhongs = khoaPhongs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(Serializable tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getKhoaPhongs() {
        return this.khoaPhongs;
    }
    
    public void setKhoaPhongs(Set khoaPhongs) {
        this.khoaPhongs = khoaPhongs;
    }




}


