package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiHoatDong generated by hbm2java
 */
public class LoaiHoatDong  implements java.io.Serializable {


     private int id;
     private Serializable tenLoai;
     private Set hoatDongs = new HashSet(0);

    public LoaiHoatDong() {
    }

	
    public LoaiHoatDong(int id) {
        this.id = id;
    }
    public LoaiHoatDong(int id, Serializable tenLoai, Set hoatDongs) {
       this.id = id;
       this.tenLoai = tenLoai;
       this.hoatDongs = hoatDongs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(Serializable tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getHoatDongs() {
        return this.hoatDongs;
    }
    
    public void setHoatDongs(Set hoatDongs) {
        this.hoatDongs = hoatDongs;
    }




}


