package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiTuyenDung generated by hbm2java
 */
public class LoaiTuyenDung  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tenLoai;
     private Set tuyenDungThongBaos = new HashSet(0);

    public LoaiTuyenDung() {
    }

	
    public LoaiTuyenDung(int id) {
        this.id = id;
    }
    public LoaiTuyenDung(int id, NgonNgu ngonNgu, Serializable tenLoai, Set tuyenDungThongBaos) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tenLoai = tenLoai;
       this.tuyenDungThongBaos = tuyenDungThongBaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(Serializable tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getTuyenDungThongBaos() {
        return this.tuyenDungThongBaos;
    }
    
    public void setTuyenDungThongBaos(Set tuyenDungThongBaos) {
        this.tuyenDungThongBaos = tuyenDungThongBaos;
    }




}


