package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MenuLeft generated by hbm2java
 */
public class MenuLeft  implements java.io.Serializable {


     private int idmenu;
     private Serializable name;
     private Serializable link;
     private Integer idparrent;
     private Integer prioty;
     private Set pageOfMenus = new HashSet(0);

    public MenuLeft() {
    }

	
    public MenuLeft(int idmenu) {
        this.idmenu = idmenu;
    }
    public MenuLeft(int idmenu, Serializable name, Serializable link, Integer idparrent, Integer prioty, Set pageOfMenus) {
       this.idmenu = idmenu;
       this.name = name;
       this.link = link;
       this.idparrent = idparrent;
       this.prioty = prioty;
       this.pageOfMenus = pageOfMenus;
    }
   
    public int getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(int idmenu) {
        this.idmenu = idmenu;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Integer getIdparrent() {
        return this.idparrent;
    }
    
    public void setIdparrent(Integer idparrent) {
        this.idparrent = idparrent;
    }
    public Integer getPrioty() {
        return this.prioty;
    }
    
    public void setPrioty(Integer prioty) {
        this.prioty = prioty;
    }
    public Set getPageOfMenus() {
        return this.pageOfMenus;
    }
    
    public void setPageOfMenus(Set pageOfMenus) {
        this.pageOfMenus = pageOfMenus;
    }




}


