package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable name;
     private Integer idparrent;
     private Integer prioty;
     private Serializable link;
     private Serializable paramId;
     private Boolean root;
     private Serializable pageName;
     private Serializable controllerName;
     private Serializable actionName;
     private Serializable menuController;
     private Serializable menuAction;
     private Set pages = new HashSet(0);

    public Menu() {
    }

	
    public Menu(int id, NgonNgu ngonNgu) {
        this.id = id;
        this.ngonNgu = ngonNgu;
    }
    public Menu(int id, NgonNgu ngonNgu, Serializable name, Integer idparrent, Integer prioty, Serializable link, Serializable paramId, Boolean root, Serializable pageName, Serializable controllerName, Serializable actionName, Serializable menuController, Serializable menuAction, Set pages) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.name = name;
       this.idparrent = idparrent;
       this.prioty = prioty;
       this.link = link;
       this.paramId = paramId;
       this.root = root;
       this.pageName = pageName;
       this.controllerName = controllerName;
       this.actionName = actionName;
       this.menuController = menuController;
       this.menuAction = menuAction;
       this.pages = pages;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Integer getIdparrent() {
        return this.idparrent;
    }
    
    public void setIdparrent(Integer idparrent) {
        this.idparrent = idparrent;
    }
    public Integer getPrioty() {
        return this.prioty;
    }
    
    public void setPrioty(Integer prioty) {
        this.prioty = prioty;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Serializable getParamId() {
        return this.paramId;
    }
    
    public void setParamId(Serializable paramId) {
        this.paramId = paramId;
    }
    public Boolean getRoot() {
        return this.root;
    }
    
    public void setRoot(Boolean root) {
        this.root = root;
    }
    public Serializable getPageName() {
        return this.pageName;
    }
    
    public void setPageName(Serializable pageName) {
        this.pageName = pageName;
    }
    public Serializable getControllerName() {
        return this.controllerName;
    }
    
    public void setControllerName(Serializable controllerName) {
        this.controllerName = controllerName;
    }
    public Serializable getActionName() {
        return this.actionName;
    }
    
    public void setActionName(Serializable actionName) {
        this.actionName = actionName;
    }
    public Serializable getMenuController() {
        return this.menuController;
    }
    
    public void setMenuController(Serializable menuController) {
        this.menuController = menuController;
    }
    public Serializable getMenuAction() {
        return this.menuAction;
    }
    
    public void setMenuAction(Serializable menuAction) {
        this.menuAction = menuAction;
    }
    public Set getPages() {
        return this.pages;
    }
    
    public void setPages(Set pages) {
        this.pages = pages;
    }




}


