package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable noiDung;
     private String keyword;
     private Serializable description;

    public Message() {
    }

	
    public Message(int id) {
        this.id = id;
    }
    public Message(int id, NgonNgu ngonNgu, Serializable noiDung, String keyword, Serializable description) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.noiDung = noiDung;
       this.keyword = keyword;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }




}


