package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NamSinh generated by hbm2java
 */
public class NamSinh  implements java.io.Serializable {


     private int id;
     private Integer nam;
     private Set hoiDapYkhoas = new HashSet(0);
     private Set henKhamBenhs = new HashSet(0);

    public NamSinh() {
    }

	
    public NamSinh(int id) {
        this.id = id;
    }
    public NamSinh(int id, Integer nam, Set hoiDapYkhoas, Set henKhamBenhs) {
       this.id = id;
       this.nam = nam;
       this.hoiDapYkhoas = hoiDapYkhoas;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNam() {
        return this.nam;
    }
    
    public void setNam(Integer nam) {
        this.nam = nam;
    }
    public Set getHoiDapYkhoas() {
        return this.hoiDapYkhoas;
    }
    
    public void setHoiDapYkhoas(Set hoiDapYkhoas) {
        this.hoiDapYkhoas = hoiDapYkhoas;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


