package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * NgonNgu generated by hbm2java
 */
public class NgonNgu  implements java.io.Serializable {


     private int id;
     private Serializable tenNgonNgu;
     private Serializable yahoo;
     private Serializable skype;
     private Serializable tenBenhVien;
     private Serializable diaChi;
     private Serializable dienThoai;
     private Serializable email;
     private Serializable headDangKy;
     private Serializable headDangNhap;
     private Serializable headSoDo;
     private Serializable flat;
     private Serializable headButton;
     private Serializable pageTitle;
     private Serializable sxemTiep;
     private Serializable stinMoiNhat;
     private Serializable slienHeKhachHang;
     private Serializable sten;
     private Serializable sdienThoai;
     private Serializable sdiaChi;
     private Serializable snoiDung;
     private Serializable smaBaoVe;
     private Serializable sgui;
     private Serializable shuy;
     private Serializable shoTro;
     private Serializable ssuKien;
     private Serializable sguiCauHoi;
     private Serializable scauHoi;
     private Serializable scauTraLoi;
     private Serializable scauHoiKhac;
     private Serializable stinTucKhac;
     private Serializable sdatLichKham;
     private Serializable keyWord;
     private Serializable description;
     private Serializable tieuDeLichKham;
     private Serializable sang;
     private Serializable chieu;
     private Serializable tieuDeNgay;
     private Set menus = new HashSet(0);
     private Set loaiCauHois = new HashSet(0);
     private Set phongKhams = new HashSet(0);
     private Set gioiThieuChiTiets = new HashSet(0);
     private Set loaiTuyenDungs = new HashSet(0);
     private Set tinTucs = new HashSet(0);
     private Set khoaPhongs = new HashSet(0);
     private Set tuyenDungThongBaos = new HashSet(0);
     private Set dichVuChiTiets = new HashSet(0);
     private Set lichNgays = new HashSet(0);
     private Set noiDungTinhChiTiets = new HashSet(0);
     private Set subMenus = new HashSet(0);
     private Set hoatDongs = new HashSet(0);
     private Set subNotes = new HashSet(0);
     private Set slideShows = new HashSet(0);
     private Set subPhones = new HashSet(0);
     private Set events = new HashSet(0);
     private Set phanHois = new HashSet(0);
     private Set videos = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set lienKetWebSites = new HashSet(0);
     private Set imagePages = new HashSet(0);
     private Set tinhTrangHonNhans = new HashSet(0);

    public NgonNgu() {
    }

	
    public NgonNgu(int id) {
        this.id = id;
    }
    public NgonNgu(int id, Serializable tenNgonNgu, Serializable yahoo, Serializable skype, Serializable tenBenhVien, Serializable diaChi, Serializable dienThoai, Serializable email, Serializable headDangKy, Serializable headDangNhap, Serializable headSoDo, Serializable flat, Serializable headButton, Serializable pageTitle, Serializable sxemTiep, Serializable stinMoiNhat, Serializable slienHeKhachHang, Serializable sten, Serializable sdienThoai, Serializable sdiaChi, Serializable snoiDung, Serializable smaBaoVe, Serializable sgui, Serializable shuy, Serializable shoTro, Serializable ssuKien, Serializable sguiCauHoi, Serializable scauHoi, Serializable scauTraLoi, Serializable scauHoiKhac, Serializable stinTucKhac, Serializable sdatLichKham, Serializable keyWord, Serializable description, Serializable tieuDeLichKham, Serializable sang, Serializable chieu, Serializable tieuDeNgay, Set menus, Set loaiCauHois, Set phongKhams, Set gioiThieuChiTiets, Set loaiTuyenDungs, Set tinTucs, Set khoaPhongs, Set tuyenDungThongBaos, Set dichVuChiTiets, Set lichNgays, Set noiDungTinhChiTiets, Set subMenus, Set hoatDongs, Set subNotes, Set slideShows, Set subPhones, Set events, Set phanHois, Set videos, Set messages, Set lienKetWebSites, Set imagePages, Set tinhTrangHonNhans) {
       this.id = id;
       this.tenNgonNgu = tenNgonNgu;
       this.yahoo = yahoo;
       this.skype = skype;
       this.tenBenhVien = tenBenhVien;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.email = email;
       this.headDangKy = headDangKy;
       this.headDangNhap = headDangNhap;
       this.headSoDo = headSoDo;
       this.flat = flat;
       this.headButton = headButton;
       this.pageTitle = pageTitle;
       this.sxemTiep = sxemTiep;
       this.stinMoiNhat = stinMoiNhat;
       this.slienHeKhachHang = slienHeKhachHang;
       this.sten = sten;
       this.sdienThoai = sdienThoai;
       this.sdiaChi = sdiaChi;
       this.snoiDung = snoiDung;
       this.smaBaoVe = smaBaoVe;
       this.sgui = sgui;
       this.shuy = shuy;
       this.shoTro = shoTro;
       this.ssuKien = ssuKien;
       this.sguiCauHoi = sguiCauHoi;
       this.scauHoi = scauHoi;
       this.scauTraLoi = scauTraLoi;
       this.scauHoiKhac = scauHoiKhac;
       this.stinTucKhac = stinTucKhac;
       this.sdatLichKham = sdatLichKham;
       this.keyWord = keyWord;
       this.description = description;
       this.tieuDeLichKham = tieuDeLichKham;
       this.sang = sang;
       this.chieu = chieu;
       this.tieuDeNgay = tieuDeNgay;
       this.menus = menus;
       this.loaiCauHois = loaiCauHois;
       this.phongKhams = phongKhams;
       this.gioiThieuChiTiets = gioiThieuChiTiets;
       this.loaiTuyenDungs = loaiTuyenDungs;
       this.tinTucs = tinTucs;
       this.khoaPhongs = khoaPhongs;
       this.tuyenDungThongBaos = tuyenDungThongBaos;
       this.dichVuChiTiets = dichVuChiTiets;
       this.lichNgays = lichNgays;
       this.noiDungTinhChiTiets = noiDungTinhChiTiets;
       this.subMenus = subMenus;
       this.hoatDongs = hoatDongs;
       this.subNotes = subNotes;
       this.slideShows = slideShows;
       this.subPhones = subPhones;
       this.events = events;
       this.phanHois = phanHois;
       this.videos = videos;
       this.messages = messages;
       this.lienKetWebSites = lienKetWebSites;
       this.imagePages = imagePages;
       this.tinhTrangHonNhans = tinhTrangHonNhans;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenNgonNgu() {
        return this.tenNgonNgu;
    }
    
    public void setTenNgonNgu(Serializable tenNgonNgu) {
        this.tenNgonNgu = tenNgonNgu;
    }
    public Serializable getYahoo() {
        return this.yahoo;
    }
    
    public void setYahoo(Serializable yahoo) {
        this.yahoo = yahoo;
    }
    public Serializable getSkype() {
        return this.skype;
    }
    
    public void setSkype(Serializable skype) {
        this.skype = skype;
    }
    public Serializable getTenBenhVien() {
        return this.tenBenhVien;
    }
    
    public void setTenBenhVien(Serializable tenBenhVien) {
        this.tenBenhVien = tenBenhVien;
    }
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }
    public Serializable getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(Serializable dienThoai) {
        this.dienThoai = dienThoai;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getHeadDangKy() {
        return this.headDangKy;
    }
    
    public void setHeadDangKy(Serializable headDangKy) {
        this.headDangKy = headDangKy;
    }
    public Serializable getHeadDangNhap() {
        return this.headDangNhap;
    }
    
    public void setHeadDangNhap(Serializable headDangNhap) {
        this.headDangNhap = headDangNhap;
    }
    public Serializable getHeadSoDo() {
        return this.headSoDo;
    }
    
    public void setHeadSoDo(Serializable headSoDo) {
        this.headSoDo = headSoDo;
    }
    public Serializable getFlat() {
        return this.flat;
    }
    
    public void setFlat(Serializable flat) {
        this.flat = flat;
    }
    public Serializable getHeadButton() {
        return this.headButton;
    }
    
    public void setHeadButton(Serializable headButton) {
        this.headButton = headButton;
    }
    public Serializable getPageTitle() {
        return this.pageTitle;
    }
    
    public void setPageTitle(Serializable pageTitle) {
        this.pageTitle = pageTitle;
    }
    public Serializable getSxemTiep() {
        return this.sxemTiep;
    }
    
    public void setSxemTiep(Serializable sxemTiep) {
        this.sxemTiep = sxemTiep;
    }
    public Serializable getStinMoiNhat() {
        return this.stinMoiNhat;
    }
    
    public void setStinMoiNhat(Serializable stinMoiNhat) {
        this.stinMoiNhat = stinMoiNhat;
    }
    public Serializable getSlienHeKhachHang() {
        return this.slienHeKhachHang;
    }
    
    public void setSlienHeKhachHang(Serializable slienHeKhachHang) {
        this.slienHeKhachHang = slienHeKhachHang;
    }
    public Serializable getSten() {
        return this.sten;
    }
    
    public void setSten(Serializable sten) {
        this.sten = sten;
    }
    public Serializable getSdienThoai() {
        return this.sdienThoai;
    }
    
    public void setSdienThoai(Serializable sdienThoai) {
        this.sdienThoai = sdienThoai;
    }
    public Serializable getSdiaChi() {
        return this.sdiaChi;
    }
    
    public void setSdiaChi(Serializable sdiaChi) {
        this.sdiaChi = sdiaChi;
    }
    public Serializable getSnoiDung() {
        return this.snoiDung;
    }
    
    public void setSnoiDung(Serializable snoiDung) {
        this.snoiDung = snoiDung;
    }
    public Serializable getSmaBaoVe() {
        return this.smaBaoVe;
    }
    
    public void setSmaBaoVe(Serializable smaBaoVe) {
        this.smaBaoVe = smaBaoVe;
    }
    public Serializable getSgui() {
        return this.sgui;
    }
    
    public void setSgui(Serializable sgui) {
        this.sgui = sgui;
    }
    public Serializable getShuy() {
        return this.shuy;
    }
    
    public void setShuy(Serializable shuy) {
        this.shuy = shuy;
    }
    public Serializable getShoTro() {
        return this.shoTro;
    }
    
    public void setShoTro(Serializable shoTro) {
        this.shoTro = shoTro;
    }
    public Serializable getSsuKien() {
        return this.ssuKien;
    }
    
    public void setSsuKien(Serializable ssuKien) {
        this.ssuKien = ssuKien;
    }
    public Serializable getSguiCauHoi() {
        return this.sguiCauHoi;
    }
    
    public void setSguiCauHoi(Serializable sguiCauHoi) {
        this.sguiCauHoi = sguiCauHoi;
    }
    public Serializable getScauHoi() {
        return this.scauHoi;
    }
    
    public void setScauHoi(Serializable scauHoi) {
        this.scauHoi = scauHoi;
    }
    public Serializable getScauTraLoi() {
        return this.scauTraLoi;
    }
    
    public void setScauTraLoi(Serializable scauTraLoi) {
        this.scauTraLoi = scauTraLoi;
    }
    public Serializable getScauHoiKhac() {
        return this.scauHoiKhac;
    }
    
    public void setScauHoiKhac(Serializable scauHoiKhac) {
        this.scauHoiKhac = scauHoiKhac;
    }
    public Serializable getStinTucKhac() {
        return this.stinTucKhac;
    }
    
    public void setStinTucKhac(Serializable stinTucKhac) {
        this.stinTucKhac = stinTucKhac;
    }
    public Serializable getSdatLichKham() {
        return this.sdatLichKham;
    }
    
    public void setSdatLichKham(Serializable sdatLichKham) {
        this.sdatLichKham = sdatLichKham;
    }
    public Serializable getKeyWord() {
        return this.keyWord;
    }
    
    public void setKeyWord(Serializable keyWord) {
        this.keyWord = keyWord;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Serializable getTieuDeLichKham() {
        return this.tieuDeLichKham;
    }
    
    public void setTieuDeLichKham(Serializable tieuDeLichKham) {
        this.tieuDeLichKham = tieuDeLichKham;
    }
    public Serializable getSang() {
        return this.sang;
    }
    
    public void setSang(Serializable sang) {
        this.sang = sang;
    }
    public Serializable getChieu() {
        return this.chieu;
    }
    
    public void setChieu(Serializable chieu) {
        this.chieu = chieu;
    }
    public Serializable getTieuDeNgay() {
        return this.tieuDeNgay;
    }
    
    public void setTieuDeNgay(Serializable tieuDeNgay) {
        this.tieuDeNgay = tieuDeNgay;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }
    public Set getLoaiCauHois() {
        return this.loaiCauHois;
    }
    
    public void setLoaiCauHois(Set loaiCauHois) {
        this.loaiCauHois = loaiCauHois;
    }
    public Set getPhongKhams() {
        return this.phongKhams;
    }
    
    public void setPhongKhams(Set phongKhams) {
        this.phongKhams = phongKhams;
    }
    public Set getGioiThieuChiTiets() {
        return this.gioiThieuChiTiets;
    }
    
    public void setGioiThieuChiTiets(Set gioiThieuChiTiets) {
        this.gioiThieuChiTiets = gioiThieuChiTiets;
    }
    public Set getLoaiTuyenDungs() {
        return this.loaiTuyenDungs;
    }
    
    public void setLoaiTuyenDungs(Set loaiTuyenDungs) {
        this.loaiTuyenDungs = loaiTuyenDungs;
    }
    public Set getTinTucs() {
        return this.tinTucs;
    }
    
    public void setTinTucs(Set tinTucs) {
        this.tinTucs = tinTucs;
    }
    public Set getKhoaPhongs() {
        return this.khoaPhongs;
    }
    
    public void setKhoaPhongs(Set khoaPhongs) {
        this.khoaPhongs = khoaPhongs;
    }
    public Set getTuyenDungThongBaos() {
        return this.tuyenDungThongBaos;
    }
    
    public void setTuyenDungThongBaos(Set tuyenDungThongBaos) {
        this.tuyenDungThongBaos = tuyenDungThongBaos;
    }
    public Set getDichVuChiTiets() {
        return this.dichVuChiTiets;
    }
    
    public void setDichVuChiTiets(Set dichVuChiTiets) {
        this.dichVuChiTiets = dichVuChiTiets;
    }
    public Set getLichNgays() {
        return this.lichNgays;
    }
    
    public void setLichNgays(Set lichNgays) {
        this.lichNgays = lichNgays;
    }
    public Set getNoiDungTinhChiTiets() {
        return this.noiDungTinhChiTiets;
    }
    
    public void setNoiDungTinhChiTiets(Set noiDungTinhChiTiets) {
        this.noiDungTinhChiTiets = noiDungTinhChiTiets;
    }
    public Set getSubMenus() {
        return this.subMenus;
    }
    
    public void setSubMenus(Set subMenus) {
        this.subMenus = subMenus;
    }
    public Set getHoatDongs() {
        return this.hoatDongs;
    }
    
    public void setHoatDongs(Set hoatDongs) {
        this.hoatDongs = hoatDongs;
    }
    public Set getSubNotes() {
        return this.subNotes;
    }
    
    public void setSubNotes(Set subNotes) {
        this.subNotes = subNotes;
    }
    public Set getSlideShows() {
        return this.slideShows;
    }
    
    public void setSlideShows(Set slideShows) {
        this.slideShows = slideShows;
    }
    public Set getSubPhones() {
        return this.subPhones;
    }
    
    public void setSubPhones(Set subPhones) {
        this.subPhones = subPhones;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getPhanHois() {
        return this.phanHois;
    }
    
    public void setPhanHois(Set phanHois) {
        this.phanHois = phanHois;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getLienKetWebSites() {
        return this.lienKetWebSites;
    }
    
    public void setLienKetWebSites(Set lienKetWebSites) {
        this.lienKetWebSites = lienKetWebSites;
    }
    public Set getImagePages() {
        return this.imagePages;
    }
    
    public void setImagePages(Set imagePages) {
        this.imagePages = imagePages;
    }
    public Set getTinhTrangHonNhans() {
        return this.tinhTrangHonNhans;
    }
    
    public void setTinhTrangHonNhans(Set tinhTrangHonNhans) {
        this.tinhTrangHonNhans = tinhTrangHonNhans;
    }




}


