package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * NoiDungTinh generated by hbm2java
 */
public class NoiDungTinh  implements java.io.Serializable {


     private int id;
     private Serializable tenNoiDung;
     private Set noiDungTinhChiTiets = new HashSet(0);

    public NoiDungTinh() {
    }

	
    public NoiDungTinh(int id) {
        this.id = id;
    }
    public NoiDungTinh(int id, Serializable tenNoiDung, Set noiDungTinhChiTiets) {
       this.id = id;
       this.tenNoiDung = tenNoiDung;
       this.noiDungTinhChiTiets = noiDungTinhChiTiets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenNoiDung() {
        return this.tenNoiDung;
    }
    
    public void setTenNoiDung(Serializable tenNoiDung) {
        this.tenNoiDung = tenNoiDung;
    }
    public Set getNoiDungTinhChiTiets() {
        return this.noiDungTinhChiTiets;
    }
    
    public void setNoiDungTinhChiTiets(Set noiDungTinhChiTiets) {
        this.noiDungTinhChiTiets = noiDungTinhChiTiets;
    }




}


