package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * NoiDungTinhChiTiet generated by hbm2java
 */
public class NoiDungTinhChiTiet  implements java.io.Serializable {


     private NoiDungTinhChiTietId id;
     private NgonNgu ngonNgu;
     private NoiDungTinh noiDungTinh;
     private User user;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable noiDung;
     private Serializable hinhAnh;
     private Date ngayChinhSua;
     private int id_1;
     private Integer luotXem;

    public NoiDungTinhChiTiet() {
    }

	
    public NoiDungTinhChiTiet(NoiDungTinhChiTietId id, NgonNgu ngonNgu, NoiDungTinh noiDungTinh, int id_1) {
        this.id = id;
        this.ngonNgu = ngonNgu;
        this.noiDungTinh = noiDungTinh;
        this.id_1 = id_1;
    }
    public NoiDungTinhChiTiet(NoiDungTinhChiTietId id, NgonNgu ngonNgu, NoiDungTinh noiDungTinh, User user, Serializable tieuDe, Serializable gioiThieu, Serializable noiDung, Serializable hinhAnh, Date ngayChinhSua, int id_1, Integer luotXem) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.noiDungTinh = noiDungTinh;
       this.user = user;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.noiDung = noiDung;
       this.hinhAnh = hinhAnh;
       this.ngayChinhSua = ngayChinhSua;
       this.id_1 = id_1;
       this.luotXem = luotXem;
    }
   
    public NoiDungTinhChiTietId getId() {
        return this.id;
    }
    
    public void setId(NoiDungTinhChiTietId id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public NoiDungTinh getNoiDungTinh() {
        return this.noiDungTinh;
    }
    
    public void setNoiDungTinh(NoiDungTinh noiDungTinh) {
        this.noiDungTinh = noiDungTinh;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getNgayChinhSua() {
        return this.ngayChinhSua;
    }
    
    public void setNgayChinhSua(Date ngayChinhSua) {
        this.ngayChinhSua = ngayChinhSua;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }




}


