package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Page generated by hbm2java
 */
public class Page  implements java.io.Serializable {


     private int idpage;
     private Menu menu;
     private Serializable namePage;
     private Boolean active;

    public Page() {
    }

	
    public Page(int idpage) {
        this.idpage = idpage;
    }
    public Page(int idpage, Menu menu, Serializable namePage, Boolean active) {
       this.idpage = idpage;
       this.menu = menu;
       this.namePage = namePage;
       this.active = active;
    }
   
    public int getIdpage() {
        return this.idpage;
    }
    
    public void setIdpage(int idpage) {
        this.idpage = idpage;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Serializable getNamePage() {
        return this.namePage;
    }
    
    public void setNamePage(Serializable namePage) {
        this.namePage = namePage;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


