package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * PageOfMenu generated by hbm2java
 */
public class PageOfMenu  implements java.io.Serializable {


     private int id;
     private MenuLeft menuLeft;
     private Serializable namePage;
     private Boolean active;

    public PageOfMenu() {
    }

	
    public PageOfMenu(int id) {
        this.id = id;
    }
    public PageOfMenu(int id, MenuLeft menuLeft, Serializable namePage, Boolean active) {
       this.id = id;
       this.menuLeft = menuLeft;
       this.namePage = namePage;
       this.active = active;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MenuLeft getMenuLeft() {
        return this.menuLeft;
    }
    
    public void setMenuLeft(MenuLeft menuLeft) {
        this.menuLeft = menuLeft;
    }
    public Serializable getNamePage() {
        return this.namePage;
    }
    
    public void setNamePage(Serializable namePage) {
        this.namePage = namePage;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


