package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private int idpermission;
     private Serializable permissionName;
     private String pageName;
     private Boolean active;
     private Set userPermissions = new HashSet(0);
     private Set groupPermissions = new HashSet(0);

    public Permission() {
    }

	
    public Permission(int idpermission) {
        this.idpermission = idpermission;
    }
    public Permission(int idpermission, Serializable permissionName, String pageName, Boolean active, Set userPermissions, Set groupPermissions) {
       this.idpermission = idpermission;
       this.permissionName = permissionName;
       this.pageName = pageName;
       this.active = active;
       this.userPermissions = userPermissions;
       this.groupPermissions = groupPermissions;
    }
   
    public int getIdpermission() {
        return this.idpermission;
    }
    
    public void setIdpermission(int idpermission) {
        this.idpermission = idpermission;
    }
    public Serializable getPermissionName() {
        return this.permissionName;
    }
    
    public void setPermissionName(Serializable permissionName) {
        this.permissionName = permissionName;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getUserPermissions() {
        return this.userPermissions;
    }
    
    public void setUserPermissions(Set userPermissions) {
        this.userPermissions = userPermissions;
    }
    public Set getGroupPermissions() {
        return this.groupPermissions;
    }
    
    public void setGroupPermissions(Set groupPermissions) {
        this.groupPermissions = groupPermissions;
    }




}


