package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * PhanHoi generated by hbm2java
 */
public class PhanHoi  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private User user;
     private Date ngayKham;
     private String maSoBenhNhan;
     private Serializable hoVaTen;
     private Serializable email;
     private Date ngaySinh;
     private Boolean gioiTinh;
     private String dienThoai;
     private Serializable noiDung;
     private Date ngayGui;
     private Boolean daXem;
     private Integer fkLoaiPhanHoi;
     private Serializable noiDungTraLoi;
     private Date ngayTraLoi;
     private Serializable diaChi;
     private Boolean isShow;
     private Serializable tieuDe;

    public PhanHoi() {
    }

	
    public PhanHoi(int id) {
        this.id = id;
    }
    public PhanHoi(int id, NgonNgu ngonNgu, User user, Date ngayKham, String maSoBenhNhan, Serializable hoVaTen, Serializable email, Date ngaySinh, Boolean gioiTinh, String dienThoai, Serializable noiDung, Date ngayGui, Boolean daXem, Integer fkLoaiPhanHoi, Serializable noiDungTraLoi, Date ngayTraLoi, Serializable diaChi, Boolean isShow, Serializable tieuDe) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.user = user;
       this.ngayKham = ngayKham;
       this.maSoBenhNhan = maSoBenhNhan;
       this.hoVaTen = hoVaTen;
       this.email = email;
       this.ngaySinh = ngaySinh;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.noiDung = noiDung;
       this.ngayGui = ngayGui;
       this.daXem = daXem;
       this.fkLoaiPhanHoi = fkLoaiPhanHoi;
       this.noiDungTraLoi = noiDungTraLoi;
       this.ngayTraLoi = ngayTraLoi;
       this.diaChi = diaChi;
       this.isShow = isShow;
       this.tieuDe = tieuDe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getNgayKham() {
        return this.ngayKham;
    }
    
    public void setNgayKham(Date ngayKham) {
        this.ngayKham = ngayKham;
    }
    public String getMaSoBenhNhan() {
        return this.maSoBenhNhan;
    }
    
    public void setMaSoBenhNhan(String maSoBenhNhan) {
        this.maSoBenhNhan = maSoBenhNhan;
    }
    public Serializable getHoVaTen() {
        return this.hoVaTen;
    }
    
    public void setHoVaTen(Serializable hoVaTen) {
        this.hoVaTen = hoVaTen;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayGui() {
        return this.ngayGui;
    }
    
    public void setNgayGui(Date ngayGui) {
        this.ngayGui = ngayGui;
    }
    public Boolean getDaXem() {
        return this.daXem;
    }
    
    public void setDaXem(Boolean daXem) {
        this.daXem = daXem;
    }
    public Integer getFkLoaiPhanHoi() {
        return this.fkLoaiPhanHoi;
    }
    
    public void setFkLoaiPhanHoi(Integer fkLoaiPhanHoi) {
        this.fkLoaiPhanHoi = fkLoaiPhanHoi;
    }
    public Serializable getNoiDungTraLoi() {
        return this.noiDungTraLoi;
    }
    
    public void setNoiDungTraLoi(Serializable noiDungTraLoi) {
        this.noiDungTraLoi = noiDungTraLoi;
    }
    public Date getNgayTraLoi() {
        return this.ngayTraLoi;
    }
    
    public void setNgayTraLoi(Date ngayTraLoi) {
        this.ngayTraLoi = ngayTraLoi;
    }
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }
    public Boolean getIsShow() {
        return this.isShow;
    }
    
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }




}


