package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PhongKham generated by hbm2java
 */
public class PhongKham  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tenPhongKham;
     private Boolean henKham;
     private Serializable ghiChuThem;
     private Set lichKhams = new HashSet(0);
     private Set henKhamBenhs = new HashSet(0);

    public PhongKham() {
    }

	
    public PhongKham(int id) {
        this.id = id;
    }
    public PhongKham(int id, NgonNgu ngonNgu, Serializable tenPhongKham, Boolean henKham, Serializable ghiChuThem, Set lichKhams, Set henKhamBenhs) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tenPhongKham = tenPhongKham;
       this.henKham = henKham;
       this.ghiChuThem = ghiChuThem;
       this.lichKhams = lichKhams;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTenPhongKham() {
        return this.tenPhongKham;
    }
    
    public void setTenPhongKham(Serializable tenPhongKham) {
        this.tenPhongKham = tenPhongKham;
    }
    public Boolean getHenKham() {
        return this.henKham;
    }
    
    public void setHenKham(Boolean henKham) {
        this.henKham = henKham;
    }
    public Serializable getGhiChuThem() {
        return this.ghiChuThem;
    }
    
    public void setGhiChuThem(Serializable ghiChuThem) {
        this.ghiChuThem = ghiChuThem;
    }
    public Set getLichKhams() {
        return this.lichKhams;
    }
    
    public void setLichKhams(Set lichKhams) {
        this.lichKhams = lichKhams;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


