package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * QuocTich generated by hbm2java
 */
public class QuocTich  implements java.io.Serializable {


     private int id;
     private Serializable tenQuocGia;
     private Set henKhamBenhs = new HashSet(0);

    public QuocTich() {
    }

	
    public QuocTich(int id) {
        this.id = id;
    }
    public QuocTich(int id, Serializable tenQuocGia, Set henKhamBenhs) {
       this.id = id;
       this.tenQuocGia = tenQuocGia;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenQuocGia() {
        return this.tenQuocGia;
    }
    
    public void setTenQuocGia(Serializable tenQuocGia) {
        this.tenQuocGia = tenQuocGia;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


