package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SlideShow generated by hbm2java
 */
public class SlideShow  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tieuDe;
     private Serializable hinhAnh;
     private Integer stt;
     private Boolean isNewtab;
     private Serializable linkEvent;
     private Boolean isLink;

    public SlideShow() {
    }

	
    public SlideShow(int id) {
        this.id = id;
    }
    public SlideShow(int id, NgonNgu ngonNgu, Serializable tieuDe, Serializable hinhAnh, Integer stt, Boolean isNewtab, Serializable linkEvent, Boolean isLink) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tieuDe = tieuDe;
       this.hinhAnh = hinhAnh;
       this.stt = stt;
       this.isNewtab = isNewtab;
       this.linkEvent = linkEvent;
       this.isLink = isLink;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Boolean getIsNewtab() {
        return this.isNewtab;
    }
    
    public void setIsNewtab(Boolean isNewtab) {
        this.isNewtab = isNewtab;
    }
    public Serializable getLinkEvent() {
        return this.linkEvent;
    }
    
    public void setLinkEvent(Serializable linkEvent) {
        this.linkEvent = linkEvent;
    }
    public Boolean getIsLink() {
        return this.isLink;
    }
    
    public void setIsLink(Boolean isLink) {
        this.isLink = isLink;
    }




}


