package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SubMenu generated by hbm2java
 */
public class SubMenu  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable name;
     private Serializable link;
     private Integer stt;

    public SubMenu() {
    }

	
    public SubMenu(int id) {
        this.id = id;
    }
    public SubMenu(int id, NgonNgu ngonNgu, Serializable name, Serializable link, Integer stt) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.name = name;
       this.link = link;
       this.stt = stt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }




}


