package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SubNote generated by hbm2java
 */
public class SubNote  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tieuDe;
     private Serializable noiDung;
     private Serializable link;
     private Serializable image;

    public SubNote() {
    }

	
    public SubNote(int id) {
        this.id = id;
    }
    public SubNote(int id, NgonNgu ngonNgu, Serializable tieuDe, Serializable noiDung, Serializable link, Serializable image) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.link = link;
       this.image = image;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Serializable getLink() {
        return this.link;
    }
    
    public void setLink(Serializable link) {
        this.link = link;
    }
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }




}


