package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SubPhone generated by hbm2java
 */
public class SubPhone  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable name;
     private Serializable soDienThoai;
     private Boolean master;

    public SubPhone() {
    }

	
    public SubPhone(int id) {
        this.id = id;
    }
    public SubPhone(int id, NgonNgu ngonNgu, Serializable name, Serializable soDienThoai, Boolean master) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.name = name;
       this.soDienThoai = soDienThoai;
       this.master = master;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(Serializable soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public Boolean getMaster() {
        return this.master;
    }
    
    public void setMaster(Boolean master) {
        this.master = master;
    }




}


