package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ThamSo generated by hbm2java
 */
public class ThamSo  implements java.io.Serializable {


     private String khoa;
     private Serializable email;
     private Serializable matKhau;

    public ThamSo() {
    }

	
    public ThamSo(String khoa) {
        this.khoa = khoa;
    }
    public ThamSo(String khoa, Serializable email, Serializable matKhau) {
       this.khoa = khoa;
       this.email = email;
       this.matKhau = matKhau;
    }
   
    public String getKhoa() {
        return this.khoa;
    }
    
    public void setKhoa(String khoa) {
        this.khoa = khoa;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(Serializable matKhau) {
        this.matKhau = matKhau;
    }




}


