package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * TinTuc generated by hbm2java
 */
public class TinTuc  implements java.io.Serializable {


     private int id;
     private LoaiTin loaiTin;
     private NgonNgu ngonNgu;
     private User userByFkUserNguoiSua;
     private User userByFkUserNguoiTao;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable hinhAnhMinhHoa;
     private Date ngayTao;
     private Serializable noiDung;
     private Integer stt;
     private Integer luotXem;
     private Serializable author;
     private Date ngaySua;

    public TinTuc() {
    }

	
    public TinTuc(int id) {
        this.id = id;
    }
    public TinTuc(int id, LoaiTin loaiTin, NgonNgu ngonNgu, User userByFkUserNguoiSua, User userByFkUserNguoiTao, Serializable tieuDe, Serializable gioiThieu, Serializable hinhAnhMinhHoa, Date ngayTao, Serializable noiDung, Integer stt, Integer luotXem, Serializable author, Date ngaySua) {
       this.id = id;
       this.loaiTin = loaiTin;
       this.ngonNgu = ngonNgu;
       this.userByFkUserNguoiSua = userByFkUserNguoiSua;
       this.userByFkUserNguoiTao = userByFkUserNguoiTao;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.hinhAnhMinhHoa = hinhAnhMinhHoa;
       this.ngayTao = ngayTao;
       this.noiDung = noiDung;
       this.stt = stt;
       this.luotXem = luotXem;
       this.author = author;
       this.ngaySua = ngaySua;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public LoaiTin getLoaiTin() {
        return this.loaiTin;
    }
    
    public void setLoaiTin(LoaiTin loaiTin) {
        this.loaiTin = loaiTin;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUserByFkUserNguoiSua() {
        return this.userByFkUserNguoiSua;
    }
    
    public void setUserByFkUserNguoiSua(User userByFkUserNguoiSua) {
        this.userByFkUserNguoiSua = userByFkUserNguoiSua;
    }
    public User getUserByFkUserNguoiTao() {
        return this.userByFkUserNguoiTao;
    }
    
    public void setUserByFkUserNguoiTao(User userByFkUserNguoiTao) {
        this.userByFkUserNguoiTao = userByFkUserNguoiTao;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getHinhAnhMinhHoa() {
        return this.hinhAnhMinhHoa;
    }
    
    public void setHinhAnhMinhHoa(Serializable hinhAnhMinhHoa) {
        this.hinhAnhMinhHoa = hinhAnhMinhHoa;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }
    public Serializable getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Serializable author) {
        this.author = author;
    }
    public Date getNgaySua() {
        return this.ngaySua;
    }
    
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }




}


