package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TrangThai generated by hbm2java
 */
public class TrangThai  implements java.io.Serializable {


     private int id;
     private Serializable tenLoaiTrangThai;
     private Set henKhamBenhs = new HashSet(0);

    public TrangThai() {
    }

	
    public TrangThai(int id) {
        this.id = id;
    }
    public TrangThai(int id, Serializable tenLoaiTrangThai, Set henKhamBenhs) {
       this.id = id;
       this.tenLoaiTrangThai = tenLoaiTrangThai;
       this.henKhamBenhs = henKhamBenhs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTenLoaiTrangThai() {
        return this.tenLoaiTrangThai;
    }
    
    public void setTenLoaiTrangThai(Serializable tenLoaiTrangThai) {
        this.tenLoaiTrangThai = tenLoaiTrangThai;
    }
    public Set getHenKhamBenhs() {
        return this.henKhamBenhs;
    }
    
    public void setHenKhamBenhs(Set henKhamBenhs) {
        this.henKhamBenhs = henKhamBenhs;
    }




}


