package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * TuyenDungThongBao generated by hbm2java
 */
public class TuyenDungThongBao  implements java.io.Serializable {


     private int id;
     private LoaiTuyenDung loaiTuyenDung;
     private NgonNgu ngonNgu;
     private User user;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable noiDung;
     private Date ngayTao;
     private Serializable hinhMinhHoa;
     private Integer stt;
     private Integer luotXem;

    public TuyenDungThongBao() {
    }

	
    public TuyenDungThongBao(int id) {
        this.id = id;
    }
    public TuyenDungThongBao(int id, LoaiTuyenDung loaiTuyenDung, NgonNgu ngonNgu, User user, Serializable tieuDe, Serializable gioiThieu, Serializable noiDung, Date ngayTao, Serializable hinhMinhHoa, Integer stt, Integer luotXem) {
       this.id = id;
       this.loaiTuyenDung = loaiTuyenDung;
       this.ngonNgu = ngonNgu;
       this.user = user;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.noiDung = noiDung;
       this.ngayTao = ngayTao;
       this.hinhMinhHoa = hinhMinhHoa;
       this.stt = stt;
       this.luotXem = luotXem;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public LoaiTuyenDung getLoaiTuyenDung() {
        return this.loaiTuyenDung;
    }
    
    public void setLoaiTuyenDung(LoaiTuyenDung loaiTuyenDung) {
        this.loaiTuyenDung = loaiTuyenDung;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(Serializable noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Serializable getHinhMinhHoa() {
        return this.hinhMinhHoa;
    }
    
    public void setHinhMinhHoa(Serializable hinhMinhHoa) {
        this.hinhMinhHoa = hinhMinhHoa;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }




}


