package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userName;
     private Group group;
     private KhoaPhong khoaPhong;
     private String passWord;
     private Serializable hoVaTen;
     private Date nearLastLogin;
     private Date lastLogin;
     private Boolean active;
     private String email;
     private Set tinTucsForFkUserNguoiSua = new HashSet(0);
     private Set events = new HashSet(0);
     private Set gioiThieuChiTiets = new HashSet(0);
     private Set noiDungTinhChiTiets = new HashSet(0);
     private Set lienHeKhachHangs = new HashSet(0);
     private Set tuyenDungThongBaos = new HashSet(0);
     private Set tinTucsForFkUserNguoiTao = new HashSet(0);
     private Set userPermissions = new HashSet(0);
     private Set hoatDongsForFkNguoiSua = new HashSet(0);
     private Set dichVuChiTiets = new HashSet(0);
     private Set hoatDongsForFkNguoiTao = new HashSet(0);
     private Set hoiDapYkhoas = new HashSet(0);
     private Set phanHois = new HashSet(0);

    public User() {
    }

	
    public User(String userName) {
        this.userName = userName;
    }
    public User(String userName, Group group, KhoaPhong khoaPhong, String passWord, Serializable hoVaTen, Date nearLastLogin, Date lastLogin, Boolean active, String email, Set tinTucsForFkUserNguoiSua, Set events, Set gioiThieuChiTiets, Set noiDungTinhChiTiets, Set lienHeKhachHangs, Set tuyenDungThongBaos, Set tinTucsForFkUserNguoiTao, Set userPermissions, Set hoatDongsForFkNguoiSua, Set dichVuChiTiets, Set hoatDongsForFkNguoiTao, Set hoiDapYkhoas, Set phanHois) {
       this.userName = userName;
       this.group = group;
       this.khoaPhong = khoaPhong;
       this.passWord = passWord;
       this.hoVaTen = hoVaTen;
       this.nearLastLogin = nearLastLogin;
       this.lastLogin = lastLogin;
       this.active = active;
       this.email = email;
       this.tinTucsForFkUserNguoiSua = tinTucsForFkUserNguoiSua;
       this.events = events;
       this.gioiThieuChiTiets = gioiThieuChiTiets;
       this.noiDungTinhChiTiets = noiDungTinhChiTiets;
       this.lienHeKhachHangs = lienHeKhachHangs;
       this.tuyenDungThongBaos = tuyenDungThongBaos;
       this.tinTucsForFkUserNguoiTao = tinTucsForFkUserNguoiTao;
       this.userPermissions = userPermissions;
       this.hoatDongsForFkNguoiSua = hoatDongsForFkNguoiSua;
       this.dichVuChiTiets = dichVuChiTiets;
       this.hoatDongsForFkNguoiTao = hoatDongsForFkNguoiTao;
       this.hoiDapYkhoas = hoiDapYkhoas;
       this.phanHois = phanHois;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public KhoaPhong getKhoaPhong() {
        return this.khoaPhong;
    }
    
    public void setKhoaPhong(KhoaPhong khoaPhong) {
        this.khoaPhong = khoaPhong;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public Serializable getHoVaTen() {
        return this.hoVaTen;
    }
    
    public void setHoVaTen(Serializable hoVaTen) {
        this.hoVaTen = hoVaTen;
    }
    public Date getNearLastLogin() {
        return this.nearLastLogin;
    }
    
    public void setNearLastLogin(Date nearLastLogin) {
        this.nearLastLogin = nearLastLogin;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTinTucsForFkUserNguoiSua() {
        return this.tinTucsForFkUserNguoiSua;
    }
    
    public void setTinTucsForFkUserNguoiSua(Set tinTucsForFkUserNguoiSua) {
        this.tinTucsForFkUserNguoiSua = tinTucsForFkUserNguoiSua;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getGioiThieuChiTiets() {
        return this.gioiThieuChiTiets;
    }
    
    public void setGioiThieuChiTiets(Set gioiThieuChiTiets) {
        this.gioiThieuChiTiets = gioiThieuChiTiets;
    }
    public Set getNoiDungTinhChiTiets() {
        return this.noiDungTinhChiTiets;
    }
    
    public void setNoiDungTinhChiTiets(Set noiDungTinhChiTiets) {
        this.noiDungTinhChiTiets = noiDungTinhChiTiets;
    }
    public Set getLienHeKhachHangs() {
        return this.lienHeKhachHangs;
    }
    
    public void setLienHeKhachHangs(Set lienHeKhachHangs) {
        this.lienHeKhachHangs = lienHeKhachHangs;
    }
    public Set getTuyenDungThongBaos() {
        return this.tuyenDungThongBaos;
    }
    
    public void setTuyenDungThongBaos(Set tuyenDungThongBaos) {
        this.tuyenDungThongBaos = tuyenDungThongBaos;
    }
    public Set getTinTucsForFkUserNguoiTao() {
        return this.tinTucsForFkUserNguoiTao;
    }
    
    public void setTinTucsForFkUserNguoiTao(Set tinTucsForFkUserNguoiTao) {
        this.tinTucsForFkUserNguoiTao = tinTucsForFkUserNguoiTao;
    }
    public Set getUserPermissions() {
        return this.userPermissions;
    }
    
    public void setUserPermissions(Set userPermissions) {
        this.userPermissions = userPermissions;
    }
    public Set getHoatDongsForFkNguoiSua() {
        return this.hoatDongsForFkNguoiSua;
    }
    
    public void setHoatDongsForFkNguoiSua(Set hoatDongsForFkNguoiSua) {
        this.hoatDongsForFkNguoiSua = hoatDongsForFkNguoiSua;
    }
    public Set getDichVuChiTiets() {
        return this.dichVuChiTiets;
    }
    
    public void setDichVuChiTiets(Set dichVuChiTiets) {
        this.dichVuChiTiets = dichVuChiTiets;
    }
    public Set getHoatDongsForFkNguoiTao() {
        return this.hoatDongsForFkNguoiTao;
    }
    
    public void setHoatDongsForFkNguoiTao(Set hoatDongsForFkNguoiTao) {
        this.hoatDongsForFkNguoiTao = hoatDongsForFkNguoiTao;
    }
    public Set getHoiDapYkhoas() {
        return this.hoiDapYkhoas;
    }
    
    public void setHoiDapYkhoas(Set hoiDapYkhoas) {
        this.hoiDapYkhoas = hoiDapYkhoas;
    }
    public Set getPhanHois() {
        return this.phanHois;
    }
    
    public void setPhanHois(Set phanHois) {
        this.phanHois = phanHois;
    }




}


