package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1



/**
 * UserPermission generated by hbm2java
 */
public class UserPermission  implements java.io.Serializable {


     private UserPermissionId id;
     private Permission permission;
     private User user;
     private Boolean allow;

    public UserPermission() {
    }

	
    public UserPermission(UserPermissionId id, Permission permission, User user) {
        this.id = id;
        this.permission = permission;
        this.user = user;
    }
    public UserPermission(UserPermissionId id, Permission permission, User user, Boolean allow) {
       this.id = id;
       this.permission = permission;
       this.user = user;
       this.allow = allow;
    }
   
    public UserPermissionId getId() {
        return this.id;
    }
    
    public void setId(UserPermissionId id) {
        this.id = id;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getAllow() {
        return this.allow;
    }
    
    public void setAllow(Boolean allow) {
        this.allow = allow;
    }




}


