package Model;
// Generated May 5, 2019 9:45:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private int id;
     private NgonNgu ngonNgu;
     private Serializable tieuDe;
     private Serializable gioiThieu;
     private Serializable duongDanFile;
     private boolean isYoutube;
     private boolean noiBat;
     private Integer luotXem;
     private Date ngayTao;
     private Serializable nguoiTao;
     private Serializable userNguoiSua;
     private Date ngaySua;
     private Integer stt;
     private Serializable hinhAnh;

    public Video() {
    }

	
    public Video(int id, NgonNgu ngonNgu, Serializable tieuDe, Serializable duongDanFile, boolean isYoutube, boolean noiBat, Date ngayTao) {
        this.id = id;
        this.ngonNgu = ngonNgu;
        this.tieuDe = tieuDe;
        this.duongDanFile = duongDanFile;
        this.isYoutube = isYoutube;
        this.noiBat = noiBat;
        this.ngayTao = ngayTao;
    }
    public Video(int id, NgonNgu ngonNgu, Serializable tieuDe, Serializable gioiThieu, Serializable duongDanFile, boolean isYoutube, boolean noiBat, Integer luotXem, Date ngayTao, Serializable nguoiTao, Serializable userNguoiSua, Date ngaySua, Integer stt, Serializable hinhAnh) {
       this.id = id;
       this.ngonNgu = ngonNgu;
       this.tieuDe = tieuDe;
       this.gioiThieu = gioiThieu;
       this.duongDanFile = duongDanFile;
       this.isYoutube = isYoutube;
       this.noiBat = noiBat;
       this.luotXem = luotXem;
       this.ngayTao = ngayTao;
       this.nguoiTao = nguoiTao;
       this.userNguoiSua = userNguoiSua;
       this.ngaySua = ngaySua;
       this.stt = stt;
       this.hinhAnh = hinhAnh;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NgonNgu getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(NgonNgu ngonNgu) {
        this.ngonNgu = ngonNgu;
    }
    public Serializable getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(Serializable tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Serializable getGioiThieu() {
        return this.gioiThieu;
    }
    
    public void setGioiThieu(Serializable gioiThieu) {
        this.gioiThieu = gioiThieu;
    }
    public Serializable getDuongDanFile() {
        return this.duongDanFile;
    }
    
    public void setDuongDanFile(Serializable duongDanFile) {
        this.duongDanFile = duongDanFile;
    }
    public boolean isIsYoutube() {
        return this.isYoutube;
    }
    
    public void setIsYoutube(boolean isYoutube) {
        this.isYoutube = isYoutube;
    }
    public boolean isNoiBat() {
        return this.noiBat;
    }
    
    public void setNoiBat(boolean noiBat) {
        this.noiBat = noiBat;
    }
    public Integer getLuotXem() {
        return this.luotXem;
    }
    
    public void setLuotXem(Integer luotXem) {
        this.luotXem = luotXem;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Serializable getNguoiTao() {
        return this.nguoiTao;
    }
    
    public void setNguoiTao(Serializable nguoiTao) {
        this.nguoiTao = nguoiTao;
    }
    public Serializable getUserNguoiSua() {
        return this.userNguoiSua;
    }
    
    public void setUserNguoiSua(Serializable userNguoiSua) {
        this.userNguoiSua = userNguoiSua;
    }
    public Date getNgaySua() {
        return this.ngaySua;
    }
    
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }
    public Serializable getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(Serializable hinhAnh) {
        this.hinhAnh = hinhAnh;
    }




}


